(() => {
  'use strict';
  const KEYS = { plan: 'gjrm-plan-v1', checks: 'gjrm-checks-v1' };
  const defaultPlan = { scenario:'original', status:'원안 유지', label:'ON SCHEDULE', summary:'예정된 타임라인을 그대로 따라갑니다.', changes:['16:30 경주루지월드 2–3회','18:45 보문뜰 저녁','20:10 서라벌탁구클럽'], meetTime:'13:00', lodging:'', joins:'', memo:'', updated:null };
  const scenarios = {
    original:{status:'원안 유지',label:'ON SCHEDULE',summary:'예정된 타임라인을 그대로 따라갑니다.',changes:['16:30 경주루지월드 2–3회','18:45 보문뜰 저녁','20:10 서라벌탁구클럽']},
    delay30:{status:'30분 이내 지연',label:'HOLD THE LINE',summary:'정차 시간을 조절하고 원래 일정을 유지합니다.',changes:['루지 2–3회 현장 판단','18:50 발권 마감 우선 확인','저녁·탁구 순서 유지']},
    delay60:{status:'30–60분 지연',label:'SHORT CUT',summary:'루지를 2회로 줄여 저녁 이후 일정을 지킵니다.',changes:['경주루지월드 2회 (27,000원)','18:50 발권 마감 전 도착 확인','보문뜰·탁구 일정 유지']},
    late:{status:'18:20 이후 도착',label:'SKIP A REEL',summary:'루지는 건너뛰고 저녁과 탁구에 집중합니다.',changes:['경주루지월드 생략','보문뜰로 바로 이동','저녁 후 서라벌탁구클럽']},
    rainSat:{status:'토요일 우천',label:'RAIN CUT',summary:'야외 루지 대신 국립경주박물관으로 전환합니다.',changes:['국립경주박물관 관람 (토요일 20:00까지)','이후 보문뜰 저녁','서라벌탁구클럽은 현장 시간 확인']},
    sea:{status:'일요일 입수 통제',label:'DRY DAY',summary:'물에 들어가지 않고 현장에서 대체 코스를 투표합니다.',changes:['봉길대왕암해변 입수 금지 준수','해변 산책 또는 대체 장소','단체 투표: 후보 미정']}
  };
  const getPlan = () => { try { return {...defaultPlan, ...JSON.parse(localStorage.getItem(KEYS.plan) || '{}')}; } catch(e) { return {...defaultPlan}; } };
  const setPlan = plan => { localStorage.setItem(KEYS.plan, JSON.stringify(plan)); window.dispatchEvent(new CustomEvent('planchange',{detail:plan})); };
  const escapeHTML = s => String(s || '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function renderStatus(){ const p=getPlan(); document.querySelectorAll('[data-plan-status]').forEach(el=>el.textContent=p.status); document.querySelectorAll('[data-plan-label]').forEach(el=>el.textContent=p.label); }
  function toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';t.setAttribute('role','status');document.body.append(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)}
  function setupShare(){document.querySelectorAll('[data-share]').forEach(btn=>btn.addEventListener('click',async()=>{const data={title:'GYEONGJU / TWO DAYS SOUTH',text:'250KM SOUTH — 경주로 가는 길',url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('링크를 복사했습니다.')}}catch(e){if(e.name!=='AbortError')toast('주소창의 링크를 복사해 주세요.')}}))}
  function setupCountdown(){const out=document.querySelector('[data-countdown]');if(!out)return;const target=new Date('2026-07-11T13:00:00+09:00').getTime();const tick=()=>{let d=target-Date.now();if(d<=0){out.textContent='ROAD TRIP STARTED';return}const days=Math.floor(d/864e5);d%=864e5;const h=Math.floor(d/36e5);d%=36e5;const m=Math.floor(d/6e4);const s=Math.floor((d%6e4)/1000);out.textContent=`D-${days} · ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};tick();setInterval(tick,1000)}
  function setupDays(){const buttons=[...document.querySelectorAll('[data-day-button]')];buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>{const on=x===b;x.classList.toggle('active',on);x.setAttribute('aria-selected',on)});document.querySelectorAll('[data-day-panel]').forEach(p=>p.hidden=p.dataset.dayPanel!==b.dataset.dayButton)}))}
  function setupChecks(){let saved={};try{saved=JSON.parse(localStorage.getItem(KEYS.checks)||'{}')}catch(e){}document.querySelectorAll('[data-check]').forEach((box,i)=>{box.checked=!!saved[box.dataset.check];box.addEventListener('change',()=>{saved[box.dataset.check]=box.checked;localStorage.setItem(KEYS.checks,JSON.stringify(saved));toast(box.checked?'준비 완료로 표시했어요.':'체크를 해제했어요.')})})}
  function setupPlanEditor(){const grid=document.querySelector('[data-scenarios]');if(!grid)return;let plan=getPlan();const form=document.querySelector('[data-plan-form]');const result=document.querySelector('[data-plan-result]');const choose=id=>{const s=scenarios[id]||scenarios.original;plan={...plan,...s,scenario:id,updated:new Date().toISOString()};grid.querySelectorAll('[data-scenario]').forEach(b=>{const on=b.dataset.scenario===id;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});renderResult();setPlan(plan);renderStatus()};const renderResult=()=>{result.innerHTML=`<span class="eyebrow">ACTIVE CUT</span><h2>${escapeHTML(plan.label)}</h2><p><b>${escapeHTML(plan.status)}</b><br>${escapeHTML(plan.summary)}</p><ul>${(plan.changes||[]).map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ul>${plan.lodging?`<p><b>숙소</b><br>${escapeHTML(plan.lodging)}</p>`:'<p class="muted">숙소 미정 — 확정 전까지 비워 두세요.</p>'}`};grid.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>choose(b.dataset.scenario)));form.meetTime.value=plan.meetTime||'13:00';form.lodging.value=plan.lodging||'';form.joins.value=plan.joins||'';form.memo.value=plan.memo||'';form.addEventListener('submit',e=>{e.preventDefault();plan={...plan,meetTime:form.meetTime.value,lodging:form.lodging.value.trim(),joins:form.joins.value.trim(),memo:form.memo.value.trim(),updated:new Date().toISOString()};setPlan(plan);renderResult();toast('변경사항을 이 기기에 저장했습니다.')});document.querySelector('[data-reset]').addEventListener('click',()=>{if(!confirm('저장된 플랜과 메모를 원안으로 되돌릴까요?'))return;plan={...defaultPlan};setPlan(plan);form.reset();form.meetTime.value='13:00';choose('original');toast('원안으로 초기화했습니다.')});choose(plan.scenario)}
  document.addEventListener('DOMContentLoaded',()=>{renderStatus();setupShare();setupCountdown();setupDays();setupChecks();setupPlanEditor()});window.addEventListener('planchange',renderStatus);window.GJRM={getPlan,setPlan,toast,scenarios};
})();
