const ROUTES={
 day1:{label:'DAY 01 · SOUTHBOUND',known:'천안아산 → 경주 약 3시간 08분(정차 전 예약출발 참고) · 현지 구간 3.4km + 3.3km',points:[
  {n:1,name:'천안아산역',sub:'13:00 · 은준 + 준형 집결',lat:36.7943803,lon:127.1044991,query:'천안아산역'},
  {n:2,name:'경주루지월드',sub:'16:30–18:30 · 2–3회',lat:35.8445031,lon:129.2891009,query:'경주루지월드'},
  {n:3,name:'보문뜰',sub:'18:45–19:50 · 저녁',lat:35.8426846,lon:129.2517043,query:'보문뜰'},
  {n:4,name:'서라벌탁구클럽',sub:'20:10–21:30 · 054-777-0323',lat:35.8618323,lon:129.2233283,query:'서라벌탁구클럽'},
  {n:5,name:'경주시내 임시 허브',sub:'22:00 · 진성 합류 / 숙소 TBD',lat:35.8562,lon:129.2247,query:'경주시내'}]},
 day2:{label:'DAY 02 · TO THE SEA',known:'경주시내 임시 허브 → 해변 약 36.9km / 38분 (OSRM 계획 추정)',points:[
  {n:1,name:'경주시내 임시 허브',sub:'~12:00 · 형태 합류 + 점심 (TBD)',lat:35.8562,lon:129.2247,query:'경주시내'},
  {n:2,name:'봉길대왕암해변',sub:'14:00–17:30 · 수영 / 공식 입수 마감 19:00',lat:35.7405768,lon:129.4837825,query:'봉길대왕암해변'}]}
};
let map,routeLayer,markers=[];
const naverSearch=q=>`https://map.naver.com/p/search/${encodeURIComponent(q)}`;
const icon=n=>L.divIcon({className:'',html:`<div class="cinema-marker"><span>${n}</span></div>`,iconSize:[30,36],iconAnchor:[15,34],popupAnchor:[0,-34]});
function popup(p){return `<div class="popup"><span class="eyebrow">SCENE ${String(p.n).padStart(2,'0')}</span><h3>${p.name}</h3><p>${p.sub}</p><a class="mini-link" href="${naverSearch(p.query)}" target="_blank" rel="noopener">네이버 지도 ↗</a></div>`}
function list(route){const el=document.querySelector('[data-route-list]');el.innerHTML=route.points.map((p,i)=>`<li tabindex="0" data-point="${i}"><div class="route-num"><span>${p.n}</span></div><div class="route-item"><h3>${p.name}</h3><p>${p.sub}</p><a class="mini-link" href="${naverSearch(p.query)}" target="_blank" rel="noopener">검색 / 길찾기 ↗</a></div></li>`).join('');el.querySelectorAll('[data-point]').forEach(li=>{const open=()=>{map.flyTo(markers[+li.dataset.point].getLatLng(),14,{duration:.8});markers[+li.dataset.point].openPopup()};li.addEventListener('click',e=>{if(!e.target.closest('a'))open()});li.addEventListener('keydown',e=>{if(e.key==='Enter')open()})})}
async function showRoute(key){const r=ROUTES[key];document.querySelector('[data-summary]').textContent=r.known+' · 실제 출발 시 네이버 지도 재확인';document.querySelectorAll('[data-route-tab]').forEach(b=>{const on=b.dataset.routeTab===key;b.classList.toggle('active',on);b.setAttribute('aria-selected',on)});markers.forEach(m=>m.remove());markers=r.points.map(p=>L.marker([p.lat,p.lon],{icon:icon(p.n),title:p.name}).addTo(map).bindPopup(popup(p)));list(r);if(routeLayer)routeLayer.remove();const coords=r.points.map(p=>[p.lat,p.lon]);const fallback=()=>{routeLayer=L.polyline(coords,{color:'#a52b26',weight:4,dashArray:'9 10',opacity:.85}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[38,38]});document.querySelector('[data-route-state]').textContent='도로 경로를 불러오지 못해 지점 간 직선으로 표시했습니다.'};try{const q=r.points.map(p=>`${p.lon},${p.lat}`).join(';');const res=await fetch(`https://router.project-osrm.org/route/v1/driving/${q}?overview=full&geometries=geojson`,{signal:AbortSignal.timeout(9000)});if(!res.ok)throw Error(res.status);const data=await res.json();if(!data.routes?.[0])throw Error('empty');routeLayer=L.geoJSON(data.routes[0].geometry,{style:{color:'#a52b26',weight:5,opacity:.9}}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[38,38]});const km=(data.routes[0].distance/1000).toFixed(1),min=Math.round(data.routes[0].duration/60);document.querySelector('[data-route-state]').textContent=`OSRM 도로 경로 · 전체 ${km}km / 약 ${min}분 (교통 미반영 계획 추정)`}catch(e){fallback()}}
document.addEventListener('DOMContentLoaded',()=>{map=L.map('map',{zoomControl:false}).setView([35.9,129.2],9);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);document.querySelectorAll('[data-route-tab]').forEach(b=>b.addEventListener('click',()=>showRoute(b.dataset.routeTab)));showRoute('day1');const refreshMap=()=>map.invalidateSize({pan:false});requestAnimationFrame(refreshMap);setTimeout(refreshMap,150);setTimeout(refreshMap,700);window.addEventListener('resize',refreshMap)});
