(()=>{'use strict';
const API='https://billy-full-chambers-draft.trycloudflare.com',NAMES=['은준','준형','진성','형태'],STREETS=['PREFLOP','FLOP','TURN','RIVER'];let me=sessionStorage.getItem('gj-poker-player')||'',g=null,timer=null;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],fmt=v=>Number(v||0).toLocaleString('ko-KR');
async function req(path,body){const r=await fetch(API+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify({...body,player:me}):null});const j=await r.json();if(!r.ok)throw Error(j.error||'연결 실패');return j}
function say(s,e=false){const x=$('[data-status]');if(x){x.textContent=s;x.classList.toggle('error',e)}}
async function load(quiet=false){if(!me)return gate();try{g=await req('/state?player='+encodeURIComponent(me));render();if(!quiet)say('실시간 연결됨 · 2초마다 자동 갱신')}catch(e){say('임시 게임 서버 연결 실패 · 다시 시도 중',true)}}
function gate(){$('[data-setup]').hidden=false;$('[data-poker-app]').hidden=true;const form=$('[data-setup-form]');form.innerHTML=`<div><span class="eyebrow">CHOOSE PLAYER</span><h2 class="display">누구로 입장할까요?</h2><p>각자 자기 휴대폰에서 본인 이름을 선택하세요.</p></div><div class="live-player-grid">${NAMES.map(n=>`<button type="button" data-join="${n}">${n}</button>`).join('')}</div>`;form.querySelectorAll('[data-join]').forEach(b=>b.onclick=()=>{me=b.dataset.join;sessionStorage.setItem('gj-poker-player',me);load()})}
function render(){if(!g)return;$('[data-setup]').hidden=true;$('[data-poker-app]').hidden=false;$('[data-hand-no]').textContent=g.hand;$('[data-street]').textContent=STREETS[g.street];$('[data-pot]').textContent=fmt(g.pot);const high=Math.max(...g.players.map(p=>p.roundBet));$('[data-table]').innerHTML=g.players.map((p,i)=>`<article class="poker-seat${p.folded?' folded':''}${p.allIn?' allin':''}${i===g.turn?' selected':''}"><span class="seat-marker">${i===g.dealer?'D':i===(g.dealer+1)%4?'SB':i===(g.dealer+2)%4?'BB':''}</span><b>${p.name}${p.name===me?' · 나':''}</b><strong>${fmt(p.stack)}</strong><small>${p.folded?'FOLD':p.allIn?'ALL IN':`베팅 ${fmt(p.roundBet)}`}</small>${p.pendingRebuy?`<em>리바이 ${fmt(p.pendingRebuy)} 요청 중</em>`:''}</article>`).join('');
 const mine=g.players.find(p=>p.name===me),myTurn=g.players[g.turn]?.name===me;$('[data-bet-panel]').hidden=false;$('[data-selected-name]').textContent=myTurn?`${me} 차례`:`${g.players[g.turn]?.name||'—'} 차례`;$('[data-selected-bet]').textContent=fmt(mine.roundBet);$('[data-call-amount]').textContent=fmt(Math.min(mine.stack,Math.max(0,high-mine.roundBet)));$('[data-selected-stack]').textContent=fmt(mine.stack);$$('[data-action]').forEach(b=>b.disabled=!myTurn);$('[data-chip-presets]').innerHTML=[g.bigBlind,Math.max(g.bigBlind,Math.round(g.pot/2)),g.pot].filter((v,i,a)=>v&&a.indexOf(v)===i).map(v=>`<button type="button" data-v="${v}">${fmt(v)}</button>`).join('');$$('[data-v]').forEach(b=>b.onclick=()=> $('[data-bet-input]').value=b.dataset.v);
 document.querySelector('.poker-toolbar-actions').innerHTML=`<button class="mini-link" type="button" data-change>사용자 변경</button>${g.isHost?'<button class="mini-link" type="button" data-reset>새 게임</button>':''}`;$('[data-change]').onclick=()=>{sessionStorage.removeItem('gj-poker-player');me='';gate()};if($('[data-reset]'))$('[data-reset]').onclick=()=>confirm('모든 기록을 지울까요?')&&send({type:'reset'});
 $('[data-next-street]').hidden=!g.isHost;$('[data-show-winner]').hidden=!g.isHost;$('[data-log]').innerHTML=g.log.map(x=>`<li><span>#${x.hand} · ${x.time}</span>${x.text}</li>`).join('');renderRebuy();renderCash();}
async function send(body){try{g=await req('/action',body);render();say('저장 완료 · 모두의 휴대폰에 반영됩니다.')}catch(e){say(e.message,true);await load(true)}}
function renderRebuy(){let box=$('[data-live-rebuy]');if(!box){box=document.createElement('section');box.dataset.liveRebuy='';box.className='winner-panel';document.querySelector('.poker-settlement').before(box)}const pending=g.players.filter(p=>p.pendingRebuy);box.innerHTML=`<span class="eyebrow">REBUY</span><h3>베팅금 추가</h3><div class="rebuy-row"><input data-rebuy-amount type="number" inputmode="numeric" min="100" step="100" value="5000"><button class="button poker-primary" data-rebuy>리바이 요청</button></div>${g.isHost&&pending.length?`<div class="rebuy-requests">${pending.map(p=>`<button data-approve="${p.name}">${p.name} ${fmt(p.pendingRebuy)}칩 승인</button>`).join('')}</div>`:''}`;box.querySelector('[data-rebuy]').onclick=()=>send({type:'rebuy-request',amount:Number(box.querySelector('[data-rebuy-amount]').value)});box.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>send({type:'rebuy-approve',target:b.dataset.approve}))}
function renderCash(){const value=Number($('[data-cash-form]').chipValue.value)||1;$('[data-cash-results]').innerHTML=g.players.map(p=>{const invested=10000+p.rebuy,delta=(p.stack-invested)*value;return `<article class="${delta>0?'receive':delta<0?'pay':''}"><b>${p.name}</b><span>${fmt(p.stack)}칩 · 리바이 ${fmt(p.rebuy)}</span><strong>${delta>0?'+':delta<0?'−':''}${fmt(Math.abs(delta))}원</strong><small>${delta>0?'받을 돈':delta<0?'낼 돈':'본전'}</small></article>`}).join('')+(g.pot?`<p class="cash-pending">현재 팟 ${fmt(g.pot)}칩은 지급 후 정산됩니다.</p>`:'')}
document.addEventListener('DOMContentLoaded',()=>{if(!me)gate();else load();$$('[data-action]').forEach(b=>b.onclick=()=>{const type=b.dataset.action,body={type};if(type==='bet')body.amount=Number($('[data-bet-input]').value);send(body)});$('[data-next-street]').onclick=()=>send({type:'next-street'});$('[data-show-winner]').onclick=()=>{const p=$('[data-winner-panel]');p.hidden=!p.hidden;if(!p.hidden)$('[data-winner-grid]').innerHTML=g.players.filter(x=>!x.folded).map(x=>`<label><input type="checkbox" value="${x.name}"><span>${x.name}</span></label>`).join('')};$('[data-award]').onclick=()=>send({type:'award',winners:$$('[data-winner-grid] input:checked').map(x=>x.value)});$('[data-close-bet]').hidden=true;$('[data-undo]').hidden=true;$('[data-new-game]').hidden=true;$('[data-cash-form]').onsubmit=e=>{e.preventDefault();renderCash()};$('[data-cash-form]').chipValue.oninput=renderCash;timer=setInterval(()=>load(true),2000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load(true)})})})();
