(() => {
'use strict';
const KEY='gj-poker-v1', HISTORY_LIMIT=30, streets=['PREFLOP','FLOP','TURN','RIVER'];
let game=null, snapshots=[], selected=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const n=v=>Number(v)||0, fmt=v=>Math.round(v).toLocaleString('ko-KR');
const clone=v=>JSON.parse(JSON.stringify(v));
const els={};
function save(){localStorage.setItem(KEY,JSON.stringify(game));}
function snapshot(){snapshots.push(clone(game));if(snapshots.length>HISTORY_LIMIT)snapshots.shift();}
function status(text){els.status.textContent=text;}
function log(text){game.log.unshift({hand:game.hand,text,time:new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})});game.log=game.log.slice(0,50);}
function activePlayers(){return game.players.filter(p=>!p.folded);}
function maxBet(){return Math.max(0,...game.players.map(p=>p.roundBet));}
function putChips(player,amount){amount=Math.max(0,Math.min(player.stack,Math.round(amount)));player.stack-=amount;player.roundBet+=amount;game.pot+=amount;if(player.stack===0)player.allIn=true;return amount;}
function render(){if(!game)return;els.setup.hidden=true;els.app.hidden=false;els.hand.textContent=game.hand;els.street.textContent=streets[game.street];els.pot.textContent=fmt(game.pot);els.table.innerHTML=game.players.map((p,i)=>`<button class="poker-seat${p.folded?' folded':''}${p.allIn?' allin':''}${selected===p.id?' selected':''}" data-player="${p.id}" ${p.folded?'disabled':''}><span class="seat-marker">${i===game.dealer?'D':i===(game.dealer+1)%game.players.length?'SB':i===(game.dealer+2)%game.players.length?'BB':''}</span><b>${p.name}</b><strong>${fmt(p.stack)}</strong><small>${p.folded?'FOLD':p.allIn?'ALL IN':`베팅 ${fmt(p.roundBet)}`}</small></button>`).join('');
els.table.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>openBet(b.dataset.player));
els.log.innerHTML=game.log.map(x=>`<li><span>#${x.hand} · ${x.time}</span>${x.text}</li>`).join('')||'<li>아직 기록이 없습니다.</li>';renderCash();if(selected)openBet(selected,false);else els.betPanel.hidden=true;
}
function openBet(id,rerender=true){selected=id;const p=game.players.find(x=>x.id===id);if(!p||p.folded){selected=null;els.betPanel.hidden=true;return;}if(rerender)render();els.betPanel.hidden=false;els.selectedName.textContent=p.name;els.selectedBet.textContent=fmt(p.roundBet);els.callAmount.textContent=fmt(Math.min(p.stack,Math.max(0,maxBet()-p.roundBet)));els.selectedStack.textContent=fmt(p.stack);els.betInput.value='';const call=Math.max(0,maxBet()-p.roundBet);const presets=[game.bigBlind,game.pot?Math.max(game.bigBlind,Math.round(game.pot/2)):game.bigBlind*2,game.pot||game.bigBlind*3].filter((v,i,a)=>v>0&&v<=p.stack&&a.indexOf(v)===i);els.presets.innerHTML=presets.map(v=>`<button type="button" data-amount="${v}">${v===call?'콜 ':''}${fmt(v)}</button>`).join('');els.presets.querySelectorAll('button').forEach(b=>b.onclick=()=>els.betInput.value=b.dataset.amount);}
function act(type){const p=game.players.find(x=>x.id===selected);if(!p)return;snapshot();if(type==='fold'){p.folded=true;log(`${p.name} 폴드`);selected=null;status(`${p.name}이 폴드했습니다.`);}else if(type==='check-call'){const amount=putChips(p,Math.max(0,maxBet()-p.roundBet));log(`${p.name} ${amount?`${fmt(amount)} 콜`:'체크'}`);status(amount?`${p.name}이 ${fmt(amount)} 콜했습니다.`:`${p.name}이 체크했습니다.`);}else if(type==='bet'){const amount=n(els.betInput.value);if(amount<=0){snapshots.pop();status('추가로 베팅할 금액을 입력하세요.');els.betInput.focus();return;}const paid=putChips(p,amount);log(`${p.name} ${fmt(paid)} 베팅`);status(`${p.name}이 ${fmt(paid)} 베팅했습니다.`);}else if(type==='all-in'){const paid=putChips(p,p.stack);log(`${p.name} ${fmt(paid)} 올인`);status(`${p.name} 올인!`);}save();render();}
function nextStreet(){if(game.street>=3){status('리버까지 끝났습니다. 승자를 선택해 팟을 지급하세요.');els.winnerPanel.hidden=false;renderWinners();return;}snapshot();game.street++;game.players.forEach(p=>p.roundBet=0);selected=null;log(`${streets[game.street]} 시작`);status(`${streets[game.street]} 라운드입니다.`);save();render();}
function renderWinners(){const alive=activePlayers();els.winnerGrid.innerHTML=alive.map(p=>`<label><input type="checkbox" value="${p.id}"><span>${p.name}</span></label>`).join('');}
function award(){const ids=$$('[data-winner-grid] input:checked').map(x=>x.value);if(!ids.length){status('승자를 한 명 이상 선택하세요.');return;}snapshot();const winners=ids.map(id=>game.players.find(p=>p.id===id));const pot=game.pot, base=Math.floor(pot/winners.length), remainder=pot-base*winners.length;winners.forEach((p,i)=>p.stack+=base+(i<remainder?1:0));log(`${winners.map(p=>p.name).join(' · ')} 팟 ${fmt(pot)} 획득`);game.pot=0;game.hand++;game.street=0;game.dealer=(game.dealer+1)%game.players.length;game.players.forEach(p=>{p.roundBet=0;p.folded=false;p.allIn=p.stack===0;});selected=null;els.winnerPanel.hidden=true;postBlinds();status(`${winners.map(p=>p.name).join(', ')}에게 팟을 지급하고 새 핸드를 시작했습니다.`);save();render();}
function postBlinds(){const live=game.players.filter(p=>p.stack>0);if(live.length<2){status('칩이 있는 플레이어가 부족합니다. 최종 정산을 확인하세요.');return;}const sb=game.players[(game.dealer+1)%game.players.length],bb=game.players[(game.dealer+2)%game.players.length];const a=putChips(sb,game.smallBlind),b=putChips(bb,game.bigBlind);log(`${sb.name} SB ${fmt(a)} · ${bb.name} BB ${fmt(b)}`);}
function undo(){if(!snapshots.length){status('취소할 작업이 없습니다.');return;}game=snapshots.pop();selected=null;save();status('마지막 작업을 취소했습니다.');render();}
function renderCash(){if(!game)return;const value=n(els.cashForm.chipValue.value)||1;els.cashResults.innerHTML=game.players.map(p=>{const delta=(p.stack-game.startStack)*value;return `<article class="${delta>0?'receive':delta<0?'pay':''}"><b>${p.name}</b><span>${fmt(p.stack)}칩</span><strong>${delta>0?'+':delta<0?'−':''}${fmt(Math.abs(delta))}원</strong><small>${delta>0?'받을 돈':delta<0?'낼 돈':'본전'}</small></article>`;}).join('')+(game.pot?`<p class="cash-pending">현재 팟 ${fmt(game.pot)}칩은 아직 승자가 없어 정산에서 보류 중입니다. 팟 지급 후 최종 정산하세요.</p>`:'');}
function newGame(){if(game&&!confirm('현재 게임 기록을 지우고 새로 시작할까요?'))return;localStorage.removeItem(KEY);game=null;selected=null;snapshots=[];els.app.hidden=true;els.setup.hidden=false;}
function start(e){e.preventDefault();const fd=new FormData(e.currentTarget),players=fd.getAll('players');if(players.length<2){alert('참가자를 두 명 이상 선택하세요.');return;}const stack=n(fd.get('stack')),sb=n(fd.get('smallBlind')),bb=n(fd.get('bigBlind'));if(!stack||!sb||bb<=sb||stack<bb){alert('시작 칩과 블라인드 금액을 확인하세요.');return;}game={hand:1,street:0,dealer:0,pot:0,startStack:stack,smallBlind:sb,bigBlind:bb,players:players.map((name,i)=>({id:`p${i}`,name,stack,roundBet:0,folded:false,allIn:false})),log:[]};postBlinds();save();status('블라인드를 자동 차감했습니다. 액션할 사람을 선택하세요.');render();}
document.addEventListener('DOMContentLoaded',()=>{Object.assign(els,{setup:$('[data-setup]'),setupForm:$('[data-setup-form]'),app:$('[data-poker-app]'),hand:$('[data-hand-no]'),street:$('[data-street]'),pot:$('[data-pot]'),status:$('[data-status]'),table:$('[data-table]'),betPanel:$('[data-bet-panel]'),selectedName:$('[data-selected-name]'),selectedBet:$('[data-selected-bet]'),callAmount:$('[data-call-amount]'),selectedStack:$('[data-selected-stack]'),betInput:$('[data-bet-input]'),presets:$('[data-chip-presets]'),winnerPanel:$('[data-winner-panel]'),winnerGrid:$('[data-winner-grid]'),log:$('[data-log]'),cashForm:$('[data-cash-form]'),cashResults:$('[data-cash-results]')});els.setupForm.onsubmit=start;$$('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));$('[data-close-bet]').onclick=()=>{selected=null;render();};$('[data-next-street]').onclick=nextStreet;$('[data-show-winner]').onclick=()=>{els.winnerPanel.hidden=!els.winnerPanel.hidden;if(!els.winnerPanel.hidden)renderWinners();};$('[data-award]').onclick=award;$('[data-undo]').onclick=undo;$('[data-new-game]').onclick=newGame;els.cashForm.onsubmit=e=>{e.preventDefault();renderCash();status('최종 정산을 다시 계산했습니다.');};els.cashForm.chipValue.oninput=renderCash;try{game=JSON.parse(localStorage.getItem(KEY));}catch{}if(game){els.setup.hidden=true;els.app.hidden=false;status('저장된 게임을 이어서 진행합니다.');render();}});
})();
